sonar.projectKey=OpenEdgeLittleApp
sonar.projectName=OpenEdgeLittleApp
sonar.sources=.

# OpenEdge
sonar.oe.file.suffixes=p,w,i,cls

# List ALL folders that hold .i / .p / .w / .cls (plus project root ".")
# Windows:
sonar.oe.propath=.;datasets;business;data;entities;exceptions;test;test/unit

# If you run on Linux/macOS, switch separators:
# sonar.oe.propath=.:datasets:business:data:entities:exceptions:test:test/unit

# (Optional) help Sonar classify tests
sonar.tests=test;test/unit
