sonar.projectKey=OpenEdgeLittleApp
sonar.projectName=OpenEdgeLittleApp

# Sources
sonar.sources=.

# Tell the OE plugin where to find ABL sources and includes
sonar.oe.file.suffixes=p,w,i,cls
# On Windows, use ';' between entries; on Linux/macOS, use ':'
sonar.oe.propath=.;datasets

# Optional but helpful if you have test folders:
# sonar.tests=test;test/unit
