#
b C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Schema Area":6,64;1 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Data Area":10,256;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Index Area":20,32;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "LOB Area":30,32;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Audit Data Area":40,256;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Audit Index Area":50,32;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Change Data Area":60,256;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
d "Change Index Area":70,32;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
#
e "Encryption Policy Area":80,32;8 C:\OpenEdge\WRK\OpenEdgeLittleApp\db\
